const HomeActionTypes = {
    GET_ALL_START: 'GET_ALL_START',
    GET_ALL_SUCCESS: 'GET_ALL_SUCCESS',
    GET_ALL_FAIL: 'GET_ALL_FAIL',

    GET_ALL_MY_START: 'GET_ALL_MY_START',
    GET_ALL_MY_SUCCESS: 'GET_ALL_MY_SUCCESS',
    GET_ALL_MY_FAIL: 'GET_ALL_MY_FAIL',
}

export default HomeActionTypes