# Generated by Django 3.0.7 on 2020-09-06 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200904_1650'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table='Notification',
        ),
    ]
