# Generated by Django 3.0.7 on 2020-09-06 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allcoursecertificate',
            table='AllCourseCertificate',
        ),
        migrations.AlterModelTable(
            name='certificate',
            table='Certificate',
        ),
        migrations.AlterModelTable(
            name='studentcertificate',
            table='StudentCertificate',
        ),
    ]
