# Generated by Django 3.0.7 on 2020-09-06 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_auto_20200906_1020'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='certificate',
            table='Certificate',
        ),
        migrations.AlterModelTable(
            name='studentcertificate',
            table='StudentCertificate',
        )
    ]
