# Generated by Django 3.0.7 on 2020-09-06 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_auto_20200906_1022'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allcoursecertificate',
            table='AllCourseCertificate',
        ),
    ]
