# Generated by Django 3.0.7 on 2020-09-06 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_auto_20200906_1130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllCourseCertificate',
        ),
    ]
