const CourseActionTypes = {
    FETCH_COURSES_START: 'FETCH_COURSES_START',
    FETCH_COURSES_SUCCESS: 'FETCH_COURSES_SUCCESS',
    FETCH_COURSES_FAIL: 'FETCH_COURSES_FAIL',

    SEARCH_COURSE_START: 'SEARCH_COURSE_START',
    SEARCH_COURSE_SUCCESS: 'SEARCH_COURSE_SUCCESS',
    SEARCH_COURSE_FAIL: 'SEARCH_COURSE_FAIL',

    FETCH_COURSE_DETAIL_START: 'FETCH_COURSE_DETAIL_START',
    FETCH_COURSE_DETAIL_SUCCESS: 'FETCH_COURSE_DETAIL_SUCCESS',
    FETCH_COURSE_DETAIL_FAIL: 'FETCH_COURSE_DETAIL_FAIL',

    BUY_COURSE_START: 'BUY_COURSE_START',
    BUY_COURSE_SUCCESS: 'BUY_COURSE_SUCCESS',
    BUY_COURSE_FAIL: 'BUY_COURSE_FAIL',

};

export default CourseActionTypes