const CourseActionTypes = {
    FETCH_COURSES_START: 'FETCH_COURSES_START',
    FETCH_COURSES_SUCCESS: 'FETCH_COURSES_SUCCESS',
    FETCH_COURSES_FAIL: 'FETCH_COURSE_FAIL',

    SEARCH_COURSE_START: 'SEARCH_COURSE_START',
    SEARCH_COURSE_SUCCESS: 'SEARCH_COURSE_SUCCESS',
    SEARCH_COURSE_FAIL: 'SEARCH_COURSE_FAIL',

}

export default CourseActionTypes