# Generated by Django 3.0.3 on 2020-03-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20200326_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
