# Generated by Django 3.0.3 on 2020-04-01 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_program_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_programs', to='programs.Field'),
        ),
    ]
