# Generated by Django 3.0.3 on 2020-04-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20200401_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
