# Generated by Django 3.0.3 on 2020-04-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_auto_20200401_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
