# Generated by Django 3.0.3 on 2020-04-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_field_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='field/icon'),
        ),
        migrations.AlterField(
            model_name='program',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='programs/icon'),
        ),
    ]
