# Generated by Django 3.0.3 on 2020-04-05 04:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_program_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='benefits',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='pre_requisites',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='full_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
