# Generated by Django 3.0.3 on 2020-04-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_auto_20200405_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
