# Generated by Django 3.0.3 on 2020-05-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_field_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='price',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
