# Generated by Django 3.0.7 on 2020-08-23 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0013_auto_20200611_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserViewProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date', models.DateField(default=django.utils.timezone.now)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_user_viewed', to='programs.Program')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs_viewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='program_views', through='programs.UserViewProgram', to=settings.AUTH_USER_MODEL),
        ),
    ]
