# Generated by Django 3.0.7 on 2020-08-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0015_studentprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
