# Generated by Django 3.0.7 on 2020-08-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0016_program_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprogram',
            name='status',
            field=models.CharField(blank=True, choices=[('on_going', 'On Going'), ('completed', 'Completed'), ('aborted', 'Aborted')], default='on_going', max_length=20, null=True),
        ),
    ]
