# Generated by Django 3.0.7 on 2020-08-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0017_auto_20200830_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='discount_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
