# Generated by Django 3.0.7 on 2020-08-30 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0018_program_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='students',
            field=models.ManyToManyField(related_name='student_programs', through='programs.StudentProgram', to=settings.AUTH_USER_MODEL),
        ),
    ]
