# Generated by Django 3.0.7 on 2020-08-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0019_program_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprogram',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
