# Generated by Django 3.0.7 on 2020-09-01 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0020_auto_20200831_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogram',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/program/files'),
        ),
        migrations.AlterUniqueTogether(
            name='userbuyprogram',
            unique_together={('user', 'program')},
        ),
    ]
