# Generated by Django 3.0.7 on 2020-09-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0021_auto_20200901_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbuyprogram',
            name='money',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
