# Generated by Django 3.0.7 on 2020-09-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0023_auto_20200905_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='program',
            name='price',
        ),
    ]
