# Generated by Django 3.0.7 on 2020-09-06 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0024_auto_20200905_2207'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='field',
            table='Field',
        ),
        migrations.AlterModelTable(
            name='program',
            table='Program',
        ),
        migrations.AlterModelTable(
            name='studentprogram',
            table='StudentProgram',
        ),
        migrations.AlterModelTable(
            name='userbuyprogram',
            table='UserBuyProgram',
        ),
        migrations.AlterModelTable(
            name='userviewprogram',
            table='UserViewProgram',
        ),
    ]
