# Generated by Django 3.0.3 on 2020-03-29 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20200329_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='course',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='program',
        ),
    ]
