# Generated by Django 3.0.7 on 2020-09-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_auto_20200329_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='code',
        ),
    ]
