# Generated by Django 3.0.7 on 2020-09-06 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0007_auto_20200906_0933'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='searchkeyword',
            table='SearchKeyWord',
        ),
    ]
