# Generated by Django 3.0.3 on 2020-05-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
