# Generated by Django 3.0.7 on 2020-08-15 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_auto_20200809_0946'),
        ('forums', '0004_auto_20200808_1123'),
    ]

    operations = [
    ]
