# Generated by Django 3.0.7 on 2020-09-04 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_merge_20200815_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
