# Generated by Django 3.0.7 on 2020-09-06 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_auto_20200904_2152'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='forum',
            table='Forum',
        ),
        migrations.AlterModelTable(
            name='thread',
            table='Thread',
        ),
        migrations.AlterModelTable(
            name='threadresponse',
            table='ThreadResponse',
        ),
    ]
