# Generated by Django 3.0.3 on 2020-03-26 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='resource/icon')),
                ('is_lesson_resource', models.BooleanField(default=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('resource_type', models.CharField(choices=[('video', 'video'), ('sound', 'sound'), ('doc', 'doc'), ('img', 'img')], max_length=10)),
                ('content', models.FileField(upload_to='resource/upload/%Y/%m/%d/')),
                ('status', models.BooleanField(default=True)),
                ('allow_download', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
