# Generated by Django 3.0.7 on 2020-09-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20200506_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='code',
        ),
    ]
