# Generated by Django 3.0.7 on 2020-09-06 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_remove_resource_code'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resource',
            table='Resource',
        ),
    ]
