# Generated by Django 3.0.3 on 2020-03-19 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_homes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('passed', 'Passed'), ('pending', 'Going to start')], default='pending', max_length=10)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('created_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('created_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_homes.Timeline')),
            ],
        ),
    ]
