const ProgramActionTypes = {
    FETCH_PROGRAMS_START: 'FETCH_PROGRAMS_START',
    FETCH_PROGRAMS_SUCCESS: 'FETCH_PROGRAMS_SUCCESS',
    FETCH_PROGRAMS_FAIL: 'FETCH_PROGRAMS_FAIL',
    
    FETCH_PROGRAM_DETAIL_START: 'FETCH_PROGRAM_DETAIL_START',
    FETCH_PROGRAM_DETAIL_SUCCESS: 'FETCH_PROGRAM_DETAIL_SUCCESS',
    FETCH_PROGRAM_DETAIL_FAIL: 'FETCH_PROGRAM_DETAIL_FAIL',
};

export default ProgramActionTypes