const AbilityTestTypes = {
    GENERATE_ABILITY_TEST_START: 'GENERATE_ABILITY_TEST_START',
    GENERATE_ABILITY_TEST_SUCCESS: 'GENERATE_ABILITY_TEST_SUCCESS',
    GENERATE_ABILITY_TEST_FAIL: 'GENERATE_ABILITY_TEST_FAIL',

    SUBMIT_ABILITY_TEST_START: 'SUBMIT_ABILITY_TEST_START',
    SUBMIT_ABILITY_TEST_SUCCESS: 'SUBMIT_ABILITY_TEST_SUCCESS',
    SUBMIT_ABILITY_TEST_FAIL: 'SUBMIT_ABILITY_TEST_FAIL'
};

export default AbilityTestTypes