# Generated by Django 3.0.3 on 2020-03-26 13:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('content', models.TextField()),
                ('is_right', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('content', models.TextField()),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='Level of difficult of the question')),
                ('question_type', models.CharField(choices=[('mc', 'Multi choices'), ('tf', 'True false'), ('tx', 'Paragraph text question')], default='mc', max_length=2)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('exam_type', models.CharField(choices=[('pc', 'PreCourse Test'), ('lt', 'Regular Lesson Test'), ('mc', 'Middle Course Test'), ('fc', 'Final Course Test')], max_length=2)),
                ('max_score', models.FloatField(max_length=3)),
                ('pass_score', models.FloatField(max_length=3)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_exam', to='courses.Course')),
            ],
        ),
    ]
