# Generated by Django 3.0.3 on 2020-08-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='get_result_type',
            field=models.CharField(blank=True, choices=[('best', 'Get highest result'), ('last', 'Get last result'), ('average', 'Get average result')], default='best', max_length=10),
        ),
        migrations.AddField(
            model_name='exam',
            name='max_try',
            field=models.IntegerField(default=1),
        ),
    ]
