# Generated by Django 3.0.3 on 2020-08-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20200801_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='expired_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
