# Generated by Django 3.0.3 on 2020-04-09 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20200406_1640'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0003_auto_20200409_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(related_name='question_exams', to='questions.Question'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='abilitytest',
            name='courses',
            field=models.ManyToManyField(related_name='ability_tests', to='courses.Course'),
        ),
        migrations.AddField(
            model_name='abilitytest',
            name='created_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ability_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abilitytest',
            name='modified_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ability_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abilitytest',
            name='questions',
            field=models.ManyToManyField(related_name='ability_test_questions', to='questions.Question'),
        ),
    ]
