# Generated by Django 3.0.3 on 2020-04-09 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20200406_1640'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0004_auto_20200409_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAbilityTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='abilitytest',
            old_name='time',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='abilitytest',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='abilitytest',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='abilitytest',
            name='questions',
        ),
        migrations.AddField(
            model_name='abilitytest',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ability_tests', to='courses.Course'),
        ),
        migrations.AddField(
            model_name='abilitytest',
            name='num_questions',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='abilitytest',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_responses', to='questions.Choice')),
                ('user_ability_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_responses', to='exams.UserAbilityTest')),
            ],
        ),
        migrations.AddField(
            model_name='userabilitytest',
            name='ability_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ability_user_test', to='exams.AbilityTest'),
        ),
        migrations.AddField(
            model_name='userabilitytest',
            name='questions',
            field=models.ManyToManyField(related_name='ability_questions', to='questions.Question'),
        ),
        migrations.AddField(
            model_name='userabilitytest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ability_test', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abilitytest',
            name='taken_users',
            field=models.ManyToManyField(related_name='ability_tests', through='exams.UserAbilityTest', to=settings.AUTH_USER_MODEL),
        ),
    ]
