# Generated by Django 3.0.3 on 2020-08-12 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='pass_score',
            field=models.FloatField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 13, 42, 26, 815419, tzinfo=utc), null=True),
        ),
    ]
