# Generated by Django 3.0.3 on 2020-08-12 14:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20200812_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='code',
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 14, 52, 59, 245752, tzinfo=utc), null=True),
        ),
    ]
