# Generated by Django 3.0.3 on 2020-04-10 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20200406_1640'),
        ('exams', '0006_auto_20200410_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilitytest',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ability_test', to='courses.Course'),
        ),
    ]
