# Generated by Django 3.0.7 on 2020-08-20 05:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0007_auto_20200812_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='views',
            field=models.ManyToManyField(blank=True, null=True, related_name='exam_viewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
