# Generated by Django 3.0.3 on 2020-04-14 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20200410_1100'),
        ('exams', '0008_remove_userresponse_chosen_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userabilitytest',
            name='user_responses',
            field=models.ManyToManyField(related_name='responses_users', to='questions.Choice'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_res', to='questions.Choice'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='user_ability_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_r', to='exams.UserAbilityTest'),
        ),
    ]
