# Generated by Django 3.0.7 on 2020-08-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_auto_20200820_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='enable_review',
            field=models.BooleanField(default=True),
        ),
    ]
