# Generated by Django 3.0.7 on 2020-08-21 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_homes', '0028_auto_20200820_1244'),
        ('exams', '0012_studentexamresult_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamresult',
            name='course_home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_homes.CourseHome'),
        ),
    ]
