# Generated by Django 3.0.7 on 2020-09-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_exam_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abilitytest',
            name='code',
        ),
    ]
