# Generated by Django 3.0.7 on 2020-09-06 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_remove_abilitytest_code'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='abilitytest',
            table='AbilityTest',
        ),
        migrations.AlterModelTable(
            name='exam',
            table='Exam',
        ),
        migrations.AlterModelTable(
            name='questionresponse',
            table='QuestionResponse',
        ),
        migrations.AlterModelTable(
            name='studentexam',
            table='StudentExam',
        ),
        migrations.AlterModelTable(
            name='studentexamresult',
            table='StudentExamResult',
        ),
        migrations.AlterModelTable(
            name='userabilitytest',
            table='UserAbilityTest',
        ),
        migrations.AlterModelTable(
            name='userresponse',
            table='UserResponse',
        ),
    ]
