# Generated by Django 3.0.7 on 2020-09-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_remove_abilitytest_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='mandatory',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
