# Generated by Django 3.0.7 on 2020-09-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_exam_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='pass_score',
            field=models.FloatField(blank=True, default=5.0, max_length=3, null=True),
        ),
    ]
