# Generated by Django 3.0.7 on 2020-09-06 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_auto_20200906_1020'),
        ('exams', '0016_auto_20200906_1020'),
    ]

    operations = [
    ]
