# Generated by Django 3.0.7 on 2020-09-06 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0019_auto_20200906_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexam',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_exams', to='exams.Exam'),
        ),
        migrations.AlterField(
            model_name='studentexamresult',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_exams_result', to='exams.Exam'),
        ),
        migrations.AlterField(
            model_name='studentexamresult',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_students_result', to=settings.AUTH_USER_MODEL),
        ),
    ]
