# Generated by Django 3.0.7 on 2020-09-06 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0020_auto_20200906_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='student_exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='exams.StudentExam'),
        ),
    ]
