# Generated by Django 3.0.7 on 2020-09-06 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0021_auto_20200906_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='pass_score',
            new_name='pass_percentage',
        ),
    ]
