# Generated by Django 3.0.7 on 2020-09-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0022_auto_20200906_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamresult',
            name='is_pass',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='studentexamresult',
            name='mandatory',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
