# Generated by Django 3.0.7 on 2020-09-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0023_auto_20200906_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='is_pass',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
