# Generated by Django 3.0.7 on 2020-09-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0024_studentexam_is_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='max_try',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
