# Generated by Django 3.0.7 on 2020-09-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20200906_1020'),
        ('exams', '0025_auto_20200907_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='questions',
            field=models.ManyToManyField(related_name='question_student_exams', to='questions.Question'),
        ),
    ]
