const SearchActionTypes = {
    SIMPLE_SEARCH_START: 'SIMPLE_SEARCH_START',
    SIMPLE_SEARCH_SUCCESS: 'SIMPLE_SEARCH_SUCCESS',
    SIMPLE_SEARCH_FAIL: 'SIMPLE_SEARCH_FAIL',

    ADVANCE_SEARCH_START: 'ADVANCE_SEARCH_START',
    ADVANCE_SEARCH_SUCCESS: 'ADVANCE_SEARCH_SUCCESS',
    ADVANCE_SEARCH_FAIL: 'ADVANCE_SEARCH_FAIL',
};

export default SearchActionTypes;