const SearchActionTypes = {
    SIMPLE_SEARCH_START: 'SIMPLE_SEARCH_START',
    SIMPLE_SEARCH_SUCCESS: 'SIMPLE_SEARCH_SUCCESS',
    SIMPLE_SEARCH_FAIL: 'SIMPLE_SEARCH_FAIL',

    ADVANCE_SEARCH_START: 'ADVANCE_SEARCH_START',
    ADVANCE_SEARCH_SUCCESS: 'ADVANCE_SEARCH_SUCCESS',
    ADVANCE_SEARCH_FAIL: 'ADVANCE_SEARCH_FAIL',

    GET_POPULAR_KEYWORDS_START: 'GET_POPULAR_KEYWORDS_START',
    GET_POPULAR_KEYWORDS_SUCCESS: 'GET_POPULAR_KEYWORDS_SUCCESS',
};

export default SearchActionTypes;