const SearchActionTypes = {
    SIMPLE_SEARCH_START: 'SIMPLE_SEARCH_START',
    SIMPLE_SEARCH_SUCCESS: 'SIMPLE_SEARCH_SUCCESS',
    SIMPLE_SEARCH_FAIL: 'SIMPLE_SEARCH_FAIL',

    ADVANCE_SEARCH_START: 'ADVANCE_SEARCH_START',
    ADVANCE_SEARCH_SUCCESS: 'ADVANCE_SEARCH_SUCCESS',
    ADVANCE_SEARCH_FAIL: 'ADVANCE_SEARCH_FAIL',

    GET_POPULAR_KEYWORDS_START: 'GET_POPULAR_KEYWORDS_START',
    GET_POPULAR_KEYWORDS_SUCCESS: 'GET_POPULAR_KEYWORDS_SUCCESS',

    UPDATE_SEARCH_FILTER_FIELD: 'UPDATE_SEARCH_FILTER_FIELD',
    UPDATE_SEARCH_FILTER_LEVEL: 'UPDATE_SEARCH_FILTER_LEVEL',
    UPDATE_SEARCH_FILTER_RATING: 'UPDATE_SEARCH_FILTER_RATING',
    UPDATE_SEARCH_FILTER_DATE: 'UPDATE_SEARCH_FILTER_DATE',
    UPDATE_SEARCH_FILTER_TEACHER: 'UPDATE_SEARCH_FILTER_TEACHER',
    UPDATE_SEARCH_FILTER_PRICE: 'UPDATE_SEARCH_FILTER_PRICE',
};

export default SearchActionTypes;