const AuthActionTypes = {
    LOAD_USER_START: 'LOAD_USER',
    LOAD_USER_SUCCESS: 'LOAD_USER_SUCCESS',
    LOAD_USER_FAIL: 'LOAD_USER_FAIL',
    LOAD_USER_GOOGLE_EMPTY: 'LOAD_USER_GOOGLE_EMPTY',

    REGISTER_START: 'REGISTER_START',
    REGISTER_SUCCESS: 'REGISTER_SUCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',

    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    LOGOUT_START: 'LOGOUT_START',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAIL: 'LOGOUT_FAIL',

    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
    GOOGLE_SIGN_IN_SUCCESS: 'GOOGLE_SIGN_IN_SUCCESS',

    UPDATE_ACCOUNT_START: 'UPDATE_ACCOUNT_START',
    UPDATE_ACCOUNT_SUCCESS: 'UPDATE_ACCOUNT_SUCCESS',
    UPDATE_ACCOUNT_FAIL: 'UPDATE_ACCOUNT_FAIL',
}

export default AuthActionTypes