# Generated by Django 3.0.7 on 2020-08-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200816_1236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='first_name',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='last_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='event',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='event',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='event',
            name='major',
        ),
        migrations.RemoveField(
            model_name='event',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='event',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='event',
            name='public_info',
        ),
        migrations.RemoveField(
            model_name='event',
            name='university',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='content',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='event/img'),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
