# Generated by Django 3.0.7 on 2020-09-06 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200822_1154'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='Event',
        ),
    ]
