const UIActionTypes = {
    SHOW_RL_MODAL: 'SHOW_RL_MODAL',
    HIDE_RL_MODAL: 'HIDE_RL_MODAL',
    SWITCH_RL_FORM: 'SWITCH_RL_FORM',

    TOGGLE_ABILITY_TEST_MODAL: 'TOGGLE_ABILITY_TEST_MODAL',
    TOGGLE_REGISTER_COURSE_MODAL: 'TOGGLE_REGISTER_COURSE_MODAL'
};

export default UIActionTypes