# Generated by Django 3.0.3 on 2020-03-19 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('level', models.CharField(choices=[('bg', 'Beginner'), ('im', 'Intermediate'), ('av', 'Advanced'), ('al', 'All level')], max_length=2)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('full', 'Full'), ('inactive', 'Inactive')], max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_course', to=settings.AUTH_USER_MODEL)),
                ('program', models.ManyToManyField(blank=True, related_name='program_course', to='programs.Program')),
                ('teacher', models.ManyToManyField(blank=True, limit_choices_to={'role_id': 2}, related_name='teacher_course', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose_name', models.CharField(max_length=255)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('full_description', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, help_text='What you will learn', null=True)),
                ('open_date', models.DateField(blank=True, null=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
    ]
