# Generated by Django 3.0.3 on 2020-03-28 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200326_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_detail',
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
