# Generated by Django 3.0.3 on 2020-04-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('courses', models.ManyToManyField(related_name='course_skills', to='courses.CourseDetail')),
            ],
        ),
    ]
