# Generated by Django 3.0.3 on 2020-04-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200404_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='courses',
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='skills',
            field=models.ManyToManyField(related_name='course_skills', to='courses.Skill'),
        ),
    ]
