# Generated by Django 3.0.3 on 2020-04-05 04:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20200404_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='pre_requisites',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
