# Generated by Django 3.0.3 on 2020-04-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20200406_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fee_type',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('paid', 'Paid')], max_length=10, null=True),
        ),
    ]
