# Generated by Django 3.0.3 on 2020-06-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
    ]
