# Generated by Django 3.0.3 on 2020-06-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20200607_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='outline',
            field=models.FileField(blank=True, null=True, upload_to='courses/outlines'),
        ),
    ]
