# Generated by Django 3.0.3 on 2020-06-09 15:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_course_outline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='outline',
            new_name='outline_file',
        ),
        migrations.AddField(
            model_name='course',
            name='outline_detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
