# Generated by Django 3.0.7 on 2020-08-23 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0021_auto_20200609_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserViewCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date', models.DateField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_user_viewed', to='courses.Course')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_viewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='course_viewed', through='courses.UserViewCourse', to=settings.AUTH_USER_MODEL),
        ),
    ]
