# Generated by Django 3.0.7 on 2020-08-28 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0023_auto_20200823_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('pass', 'Pass course'), ('fail', 'Fail course'), ('on_going', 'On Going')], max_length=20, null=True)),
                ('rank', models.CharField(blank=True, choices=[('medium', 'Medium'), ('good', 'Good'), ('xgood', 'Very good')], max_length=20, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(related_name='course_user', through='courses.UserCourse', to=settings.AUTH_USER_MODEL),
        ),
    ]
