# Generated by Django 3.0.7 on 2020-08-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_auto_20200828_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='status',
            field=models.CharField(blank=True, choices=[('pass', 'Pass course'), ('fail', 'Fail course'), ('on_going', 'On Going')], default='on_going', max_length=20, null=True),
        ),
    ]
