# Generated by Django 3.0.7 on 2020-08-28 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_auto_20200828_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='started_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
