# Generated by Django 3.0.7 on 2020-08-28 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_homes', '0030_auto_20200826_0924'),
        ('courses', '0026_usercourse_started_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='course_home',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_homes.CourseHome'),
        ),
    ]
