# Generated by Django 3.0.7 on 2020-08-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_auto_20200828_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='received_certificate',
            field=models.BooleanField(default=False),
        ),
    ]
