# Generated by Django 3.0.7 on 2020-08-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_auto_20200829_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='is_summarised',
            field=models.BooleanField(default=False),
        ),
    ]
