# Generated by Django 3.0.7 on 2020-08-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_auto_20200830_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
