# Generated by Django 3.0.7 on 2020-09-01 07:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0033_course_discount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbuycourse',
            unique_together={('user', 'course')},
        ),
    ]
