# Generated by Django 3.0.7 on 2020-09-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_auto_20200901_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbuycourse',
            name='money',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
