# Generated by Django 3.0.7 on 2020-09-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_userbuycourse_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='code',
        ),
    ]
