# Generated by Django 3.0.7 on 2020-09-06 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_auto_20200905_2200'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='Course',
        ),
        migrations.AlterModelTable(
            name='coursedetail',
            table='CourseDetail',
        ),
        migrations.AlterModelTable(
            name='skill',
            table='Skill',
        ),
        migrations.AlterModelTable(
            name='userbuycourse',
            table='UserBuyCourse',
        ),
        migrations.AlterModelTable(
            name='usercourse',
            table='UserCourse',
        ),
        migrations.AlterModelTable(
            name='userviewcourse',
            table='UserViewCourse',
        ),
    ]
