# Generated by Django 3.0.7 on 2020-09-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_auto_20200906_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbuycourse',
            name='in_program',
            field=models.BooleanField(default=False),
        ),
    ]
