# Generated by Django 3.0.7 on 2020-09-06 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0025_auto_20200906_1020'),
        ('courses', '0038_userbuycourse_in_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.Program'),
        ),
    ]
