# Generated by Django 3.0.7 on 2020-09-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_usercourse_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
