# Generated by Django 3.0.7 on 2020-09-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_usercourse_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbuycourse',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
