# Generated by Django 3.0.7 on 2020-09-09 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_userbuycourse_status'),
        ('courses', '0040_favoritecourse'),
    ]

    operations = [
    ]
