# Generated by Django 3.0.7 on 2020-09-10 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_merge_20200909_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritecourse',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
