# Generated by Django 3.0.7 on 2020-09-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_auto_20200911_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
