# Generated by Django 3.0.7 on 2020-09-06 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
    ]
