const CourseHomeTypes = {
    REGISTER_COURSE_START: 'REGISTER_COURSE_START',
    REGISTER_COURSE_SUCCESS: 'REGISTER_COURSE_SUCCESS',
    REGISTER_COURSE_FAIL: 'REGISTER_COURSE_FAIL',

    FETCH_MY_COURSES_START: 'FETCH_MY_COURSES_START',
    FETCH_MY_COURSES_SUCCESS: 'FETCH_MY_COURSES_SUCCESS',
    FETCH_MY_COURSES_FAIL: 'FETCH_MY_COURSES_FAIL',

};

export default CourseHomeTypes