# Generated by Django 3.0.3 on 2020-04-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_questionkit_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_kits',
            field=models.ManyToManyField(related_name='kit_questions', to='questions.QuestionKit'),
        ),
    ]
