# Generated by Django 3.0.3 on 2020-04-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20200410_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='code',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='is_answer',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(related_name='ans_questions', to='questions.Choice'),
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(related_name='questions', to='questions.Choice'),
        ),
    ]
