# Generated by Django 3.0.3 on 2020-05-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20200419_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mc', 'Multi choices'), ('tf', 'True false'), ('tx', 'Paragraph text question'), ('cb', 'Checkbox choices')], default='mc', max_length=2),
        ),
    ]
