# Generated by Django 3.0.3 on 2020-08-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20200510_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='code',
        ),
    ]
