# Generated by Django 3.0.7 on 2020-09-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_remove_question_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionkit',
            name='code',
        ),
    ]
