const ForumTypes = {
    GET_FORUMS_START: 'GET_FORUMS_START',
    GET_FORUMS_SUCCESS: 'GET_FORUMS_SUCCESS',
    GET_FORUMS_FAIL: 'GET_FORUMS_FAIL',

    GET_FORUM_DETAIL_START: 'GET_FORUM_DETAIL_START',
    GET_FORUM_DETAIL_SUCCESS: 'GET_FORUM_DETAIL_SUCCESS',
    GET_FORUM_DETAIL_FAIL: 'GET_FORUM_DETAIL_FAIL',

    GET_THREADS_START: 'GET_THREADS_START',
    GET_THREADS_SUCCESS: 'GET_THREADS_SUCCESS',
    GET_THREADS_FAIL: 'GET_THREADS_FAIL',

    GET_THREAD_DETAIL_START: 'GET_THREAD_DETAIL_START',
    GET_THREAD_DETAIL_SUCCESS: 'GET_THREAD_DETAIL_SUCCESS',
    GET_THREAD_DETAIL_FAIL: 'GET_THREAD_DETAIL_FAIL',

    CREATE_THREADS_START: 'CREATE_THREADS_START',
    CREATE_THREADS_SUCCESS: 'CREATE_THREADS_SUCCESS',
    CREATE_THREADS_FAIL: 'CREATE_THREADS_FAIL',

}

export default ForumTypes