const ForumTypes = {
    GET_FORUMS_START: 'GET_FORUMS_START',
    GET_FORUMS_SUCCESS: 'GET_FORUMS_SUCCESS',
    GET_FORUMS_FAIL: 'GET_FORUMS_FAIL',

    GET_FORUM_DETAIL_START: 'GET_FORUM_DETAIL_START',
    GET_FORUM_DETAIL_SUCCESS: 'GET_FORUM_DETAIL_SUCCESS',
    GET_FORUM_DETAIL_FAIL: 'GET_FORUM_DETAIL_FAIL',

    GET_THREADS_START: 'GET_THREADS_START',
    GET_THREADS_SUCCESS: 'GET_THREADS_SUCCESS',
    GET_THREADS_FAIL: 'GET_THREADS_FAIL',

    GET_THREAD_DETAIL_START: 'GET_THREAD_DETAIL_START',
    GET_THREAD_DETAIL_SUCCESS: 'GET_THREAD_DETAIL_SUCCESS',
    GET_THREAD_DETAIL_FAIL: 'GET_THREAD_DETAIL_FAIL',

    CREATE_THREADS_START: 'CREATE_THREADS_START',
    CREATE_THREADS_SUCCESS: 'CREATE_THREADS_SUCCESS',
    CREATE_THREADS_FAIL: 'CREATE_THREADS_FAIL',

    REPLY_THREAD_START: 'REPLY_THREAD_START',
    REPLY_THREAD_SUCCESS: 'REPLY_THREAD_SUCCESS',
    REPLY_THREAD_FAIL: 'REPLY_THREAD_FAIL',

    DELETE_THREAD_START: 'DELETE_THREAD_START',
    DELETE_THREAD_SUCCESS: 'DELETE_THREAD_SUCCESS',
    DELETE_THREAD_FAIL: 'DELETE_THREAD_FAIL',

    MODIFY_THREAD_START: 'MODIFY_THREAD_START',
    MODIFY_THREAD_SUCCESS: 'MODIFY_THREAD_SUCCESS',
    MODIFY_THREAD_FAIL: 'MODIFY_THREAD_FAIL',

    DELETE_THREAD_RESPONSE_START: 'DELETE_THREAD_RESPONSE_START',
    DELETE_THREAD_RESPONSE_SUCCESS: 'DELETE_THREAD_RESPONSE_SUCCESS',
    DELETE_THREAD_RESPONSE_FAIL: 'DELETE_THREAD_RESPONSE_FAIL',

    MODIFY_THREAD_RESPONSE_START: 'MODIFY_THREAD_RESPONSE_START',
    MODIFY_THREAD_RESPONSE_SUCCESS: 'MODIFY_THREAD_RESPONSE_SUCCESS',
    MODIFY_THREAD_RESPONSE_FAIL: 'MODIFY_THREAD_RESPONSE_FAIL',
}

export default ForumTypes