# Generated by Django 3.0.3 on 2020-03-26 13:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('modified_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], max_length=10)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('modified_date', models.DateField(auto_now=True)),
                ('course_home', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course_homes.CourseHome')),
            ],
        ),
    ]
