# Generated by Django 3.0.3 on 2020-03-26 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('course_homes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursehome',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
