# Generated by Django 3.0.3 on 2020-04-17 13:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course_homes', '0002_coursehome_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], max_length=10)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('modified_date', models.DateField(auto_now=True)),
                ('course_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_topics', to='course_homes.CourseHome')),
            ],
        ),
        migrations.CreateModel(
            name='TopicAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('file', models.FileField(upload_to='courses/home/')),
                ('status', models.BooleanField(default=True)),
                ('learning_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_assets', to='course_homes.LearningTopic')),
            ],
        ),
        migrations.DeleteModel(
            name='Timeline',
        ),
    ]
