# Generated by Django 3.0.3 on 2020-04-17 13:28

import course_homes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_homes', '0004_auto_20200417_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicasset',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=course_homes.models.asset_upload_path),
        ),
        migrations.AddField(
            model_name='topicasset',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
