# Generated by Django 3.0.3 on 2020-04-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_homes', '0005_auto_20200417_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicasset',
            name='file_type',
            field=models.CharField(blank=True, choices=[('Audio', (('mp3', 'm4a'),)), ('Video', (('mp4', 'mkv'), ('flv', 'm4v'))), ('Document', (('pdf', 'docx'), ('doc', 'xls'))), ('unknown', 'Unknown')], max_length=10, null=True),
        ),
    ]
