# Generated by Django 3.0.3 on 2020-04-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_homes', '0006_topicasset_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicasset',
            name='file_type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('doc', 'Document'), ('unknown', 'Unknown')], max_length=10, null=True),
        ),
    ]
