# Generated by Django 3.0.3 on 2020-04-17 16:07

import ckeditor.fields
import course_homes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_homes', '0007_auto_20200417_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('info', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='learningtopic',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Empty'), ('3', 'Invalid'), ('1', 'Submitted')], default='0', max_length=1)),
                ('attachment', models.FileField(upload_to=course_homes.models.assignment_upload_path)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_ass', to='course_homes.Assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ass_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='learning_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_topic_assignments', to='course_homes.LearningTopic'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='students',
            field=models.ManyToManyField(related_name='user_assignment', through='course_homes.StudentAssignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
