# Generated by Django 3.0.3 on 2020-04-18 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_homes', '0008_auto_20200417_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursehome',
            name='maximum_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursehome',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coursehome',
            name='students',
            field=models.ManyToManyField(related_name='course_homes', to=settings.AUTH_USER_MODEL),
        ),
    ]
