# Generated by Django 3.0.3 on 2020-04-19 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_homes', '0010_remove_coursehome_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicasset',
            name='code',
        ),
    ]
