# Generated by Django 3.0.3 on 2020-04-20 04:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_homes', '0011_remove_topicasset_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursehome',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='course_homes', to=settings.AUTH_USER_MODEL),
        ),
    ]
