# Generated by Django 3.0.3 on 2020-04-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_homes', '0012_auto_20200420_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursehome',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
