# Generated by Django 3.0.3 on 2020-05-04 15:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_homes', '0014_coursehome_course_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningtopic',
            name='info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
