# Generated by Django 3.0.3 on 2020-08-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_homes', '0018_coursehome_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningtopic',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], default='active', max_length=10),
        ),
    ]
