# Generated by Django 3.0.3 on 2020-08-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_homes', '0019_auto_20200803_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningtopic',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
