# Generated by Django 3.0.7 on 2020-08-18 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_homes', '0023_assignment_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='submit_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='learning_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_assignments', to='course_homes.LearningTopic'),
        ),
    ]
