# Generated by Django 3.0.7 on 2020-08-20 05:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_homes', '0026_auto_20200819_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='views',
            field=models.ManyToManyField(blank=True, null=True, related_name='assignment_viewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topicasset',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='lecture_viewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
