# Generated by Django 3.0.7 on 2020-08-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_homes', '0028_auto_20200820_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
