# Generated by Django 3.0.7 on 2020-08-26 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_homes', '0029_assignment_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicasset',
            name='file_type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('doc', 'Document'), ('pdf', 'PDF'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_homes.TopicAsset')),
            ],
        ),
        migrations.AddField(
            model_name='topicasset',
            name='student_notes',
            field=models.ManyToManyField(related_name='lecture_notes', through='course_homes.StudentNote', to=settings.AUTH_USER_MODEL),
        ),
    ]
