# Generated by Django 3.0.7 on 2020-09-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_homes', '0031_auto_20200829_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningtopic',
            name='code',
        ),
    ]
