# Generated by Django 3.0.7 on 2020-09-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_homes', '0032_remove_learningtopic_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursehome',
            name='exam_percentage',
            field=models.IntegerField(blank=True, default=80, null=True),
        ),
    ]
