# Generated by Django 3.0.7 on 2020-09-06 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_homes', '0034_assignment_mandatory'),
        ('course_homes', '0034_auto_20200906_1020'),
    ]

    operations = [
    ]
