# Generated by Django 3.0.7 on 2020-09-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_homes', '0036_auto_20200907_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
