# Generated by Django 3.0.7 on 2020-09-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_homes', '0037_auto_20200907_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcoursehome',
            name='status',
            field=models.CharField(blank=True, choices=[('pass', 'Pass course'), ('fail', 'Fail course'), ('on_going', 'On Going')], default='on_going', max_length=10, null=True),
        ),
    ]
