# Generated by Django 3.0.7 on 2020-09-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_homes', '0038_auto_20200908_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursehome',
            name='expected_date',
        ),
    ]
