const ExamTypes = {
    GET_EXAM_START: 'GET_EXAM_START',
    GET_EXAM_SUCCESS: 'GET_EXAM_SUCCESS',
    GET_EXAM_FAIL: 'GET_EXAM_FAIL',

    GET_STUDENT_EXAM_START: 'GET_STUDENT_EXAM_START',
    GET_STUDENT_EXAM_SUCCESS: 'GET_STUDENT_EXAM_SUCCESS',
    GET_STUDENT_EXAM_FAIL: 'GET_STUDENT_EXAM_FAIL',

    GET_STUDENT_EXAM_DETAIL_START: 'GET_STUDENT_EXAM_DETAIL_START',
    GET_STUDENT_EXAM_DETAIL_SUCCESS: 'GET_STUDENT_EXAM_DETAIL_SUCCESS',
    GET_STUDENT_EXAM_DETAIL_FAIL: 'GET_STUDENT_EXAM_DETAIL_FAIL',

    SUBMIT_EXAM_START: 'SUBMIT_EXAM_START',
    SUBMIT_EXAM_SUCCESS: 'SUBMIT_EXAM_SUCCESS',
    SUBMIT_EXAM_FAIL: 'SUBMIT_EXAM_FAIL',

}

export default ExamTypes