const FieldActionTypes = {
    GET_FIELD_START: 'GET_FIELD_START',
    GET_FIELD_SUCCESS: 'GET_FIELD_SUCCESS',
    GET_FIELD_FAIL: 'GET_FIELD_FAIL',

    GET_FIELD_DETAIL_START: 'GET_FIELD_DETAIL_START',
    GET_FIELD_DETAIL_SUCCESS: 'GET_FIELD_DETAIL_SUCCESS',
    GET_FIELD_DETAIL_FAIL: 'GET_FIELD_DETAIL_FAIL',

};

export default FieldActionTypes