const ProfileActionTypes = {
    GET_PROFILE_START: 'GET_PROFILE_START',
    GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
    GET_PROFILE_FAIL: 'GET_PROFILE_FAIL',

    CLEAR_CURRENT_PROFILE: 'CLEAR_CURRENT_PROFILE',

    UPDATE_PROFILE_START: 'UPDATE_PROFILE_START',
    UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_FAIL: 'UPDATE_PROFILE_FAIL',
}

export default ProfileActionTypes