const NotificationActionTypes = {
    GET_MY_NOTIFICATIONS_START: 'GET_MY_NOTIFICATIONS_START',
    GET_MY_NOTIFICATIONS_SUCCESS: 'GET_MY_NOTIFICATIONS_SUCCESS',
    GET_MY_NOTIFICATIONS_FAIL: 'GET_MY_NOTIFICATIONS_FAIL',
};

export default NotificationActionTypes